name: CI
on:
  pull_request_target:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run something dangerous
        run: |
          echo "Running as victim with elevated GITHUB_TOKEN..."
          echo "Token: ${{ secrets.GITHUB_TOKEN }}"
          echo "Custom Secret: ${{ secrets.MY_SECRET }}"
